### ISSUE TITLE
Nachos JokerDisplay crash

### ISSUE THREAD

**Issue by nh6574** [GitNether/paperback#57]
It doesn't check if the JokerDisplay object is loaded. It's a small fix so I didn't feel like PRing lol

**Comment by OppositeWolf770** [comment]
I'll get to this. Thanks 👍

**Comment by OppositeWolf770** [comment]
I'm gonna make a separate file for all the JokerDisplay definitions in a little bit, so that should all fall under a single check then. I've just got to get around to doing that 😆
